# 1. 에러 처리의 필요성
> 에러는 언제든지 발생할 수 있으며, 에러를 방치하게 되면 프로그램이 강제종료되게 된다.

에러로 인한 강제종료를 막기 위해서는 `try...catch문`을 사용해서 대응하면 프로그램이 강제 종료되지 않으며 코드를 계속해서 실행시킬 수 있게 된다.

또한 직접적인 에러 상황이 아닌 `예외`적인 상황이 발생할 수 있으며, 이러한 상황에 적절한 대응이 없다면 에러로 이어질 가능성이 크다.

따라서 언제나 에러, 예외적인 상황이 발생할 수 있다는 부분을 전제하고 이에 대응하는 코드를 짜는것이 중요하다.

<br/>

# 2. try...catch...finally문

`try...catch...finally문`의 코드블록 구조와 각각의 의미는 아래와 같다.
```js
try {
	// 실행할 코드 (에러 발생 가능성 있는 코드)
} catch (err) {
	// try 코드 블록에서 에러가 발생하면 이 코드 블록의 코드가 실행된다.
  	// err에는 try코드 블록에서 발생한 Error 객체가 전달된다.
} finally {
	// 에러 발생과 상관없이 반드시 한 번 실행된다.
}
```


<br/>

# 3. Error 객체
> Error 생성자 함수는 에러 객체를 생성하며, Error 생성자 함수에는 에러를 상세히 설명하는 에러 메세지를 인수로 전달할 수 있다.

```js
const error - new Error('invalid');
```

또한 자바스크립트는 Error 생성자 함수를 포함해 7가지의 에러 객체를 생성할 수 있는 Error 생성자 함수를 제공한다.

|생성자 함수|인스턴스|
|---|---|
|`Error`|일반적 에러 객체|
|`SyntaxError`|자바스크립트 문법에 맞지 않는 문을 해석할 때 발생하는 에러 객체|
|`ReferenceError`|참조할 수 없는 식별자를 참조했을 때 발생하는 에러 객체|
|`TypeError`|피연산자 or 인수의 데이터 타입이 유효하지 않을 때 발생 하는 에러 객체|
|`RangeError`|숫자값의 허용치 범위를 벗어났을 때 발생하는 에러 객체|
|`URIError`|encodeURI 또는 decodeURI 함수에 부적절한 인수를 전달했을 때 발생하는 에러 객체|
|`EvalError`|eval함수에서 발생하는 에러 객체|

<br/>

# 4. throw문
> throw 문의 표현식은 어떤 값이라도 상관없지만, 일반적으로 에러 객체를 지정한다.

```js
throw 표현식;
```

throw 문의 표현식은 어떤 값이라도 상관없지만, 일반적으로 에러 객체를 지정하며, 에러를 던지면 catch문의 에러 변수가 생성되고 던져진 에러 객체가 할당된다. 그리고 catch 코드 블록이 실행되기 시작한다.

